# Defines the default configuration for the CUI-Portal
portal:
  # Locale Configuration
  locale:
    # Context parameter within configuration-subsysten with the name "portal.locale.default"
    # Defines the default locale. Caution: the default locale must be defined within 
    # "portal.locale.available".
    # The default value for the is: 'de' 
    default: de
    # Context parameter within configuration-subsysten with the name "portal.locale.available" 
    # Defines the available locales for for the Portal as a comma separated list. 
    # The default value for the is: 'en,de,fr' 
    available: en,de,fr

  # Configuration sub system
  configuration:
    # Path to the Portals configuration directory.
    dir: config/

    # Scheduler
    #
    # Used for the configuration of the cron-based system for checking for changes within 
    # configuration files.
    # The configuration is done using cron-expressions. 
    # The default value for the portal is '* 0/1 * * * ?' saying the files will be scanned 
    # every minute for changes. 
    # In case of system configuration you can lower it to e.g. every 5 seconds: '0/5 * * * * ?'.
    # Always set it to a production value like every minute if you finished configuration. 
    # -Caution: Always keep in mind that this configuration change will only picked up at 
    # the next scan-interval.
    # -Caution: Due to this nature long intervals like hourly or daily can only be reconfigured 
    # with a restart or a longer time to wait.
    # -Although the reconfiguration checks the new expression and ignores it on an invalid 
    # value, the value set on start-up time must always define a correct expression, 
    # because otherwise the cron-job will not start at all.
    # -You can use Cronmaker to validate you expressions. 
    #- The actual execution of the cron job will be logged at debug level of 
    # com.icw.ehf.cui.portal.application.schedule.FileWatcherScheduler
    scheduler:
      file_cron_expression: "* 0/1 * * * ?"
    # Used for the configuration of tracking of changes in files, usually configuration files, 
    # see FileWatcherService for handling details. 
    # This is the successor of the previous cron-based approach. 
    # The default-value is true 
    file_watcher.enabled: true

    # Project-Stage
    # 
    # Used for the configuration of the Portal project stage. Defaults to 'production'.
    # Valid values are: production, test, configuration, development.
    # The mapping between Portal stages and their JSF equivalent is as follows 
    # (Portal-stage -> JSF-stage):
    # production -> Production, test -> SystemTest, 
    # configuration -> Production, development -> Development
    stage: production

  storage:
    # 1 year
    cookieMaxAge: 31536000

  session:
    # Defines the maximum interval (in minutes) the user may be inactive 
    # before we black the screen and display the idle message dialog.
    # Should correspond with "timeout". If not set, the timeout value will be used as default.
    # Technically this behavior is achieved by setting the "maxInactiveInterval" to the value '-1'.
    maxInactiveInterval: -1

    # Defines the timeout (in minutes) of the session in the jsf server.
    timeout: 20

  # Authentication
  authentication:
    # Servlet based authentication
    servlet:
      allowBasicAuth: true

smallrye:
  config:
    profile: ${portal.configuration.stage}